### ISSUE TITLE
Already generated firmware

### ISSUE THREAD

**Issue by mrmate2** [remibert/pycameresp#1]
Dear remibert, kindly asking for Your assistance and clarification.
Currently I am searching for some code, which will suit my needs while using esp32cam as security camera.
I wish to try and test your software, I have not too much but sufficient skills to compile & flash various scripts in Arduino IDE(Windows10).
Unfortunately I have zero knowledge in mycropyton scripts and compiling.
You wrote:
--------
Get a firmware already generated or see the section "Micropython firmware" to generates the firmware.
-------
As I understand it must be *.bin file, wher can I get it?
I searched all Your repository, an did not find it.
Many thanks in advance for Your reply.
Apologies fo my English, I am from Ukraine.

**Comment by remibert** [comment]
The old firmware is here https://github.com/remibert/pycameresp/releases/tag/V1, I plan to deliver in next week a version with the homekit support, not yet terminated.

**Comment by mrmate2** [comment]
Many thanks for Your teply ant pointing to the firmware file.All the best!
