### ISSUE TITLE
Homekit micropython module for esp8266/esp32

### ISSUE THREAD

**Issue by baracudaz** [remibert/pycameresp#3]
Hello and thanks for an awesome work!

Is there a way to make your Homekit implementation work as an independent MicroPython module?

I am currently using [Arduino HomeKit ESP8266](https://www.arduino.cc/reference/en/libraries/homekit-esp8266/) however I would love to see Homekit for MicroPython module. Any thoughts?

**Comment by remibert** [comment]
Hello,

The ESP8266 has less RAM and ROM than a generic ESP32. On the generic ESP32 homekit works but it is limited. On the esp32cam, which has a spiram, I was unable to get homekit to work simultaneously with the camera. I'm afraid it's hard to get homekit to work with micropython on esp8266.

**Comment by baracudaz** [comment]
Understood. However I was just wondering whether we could try it despite the constrains. Unfortunately I do not know 
much about esp32/esp32cam. However I did try the default micropython on ESP8266 in a past successfully. Not sure how to build a custom micropython distro based on your sources to include homekit. Perhaps you can navigate me?

**Comment by remibert** [comment]
I deliver scripts to easily get and recompile micropython for esp32 (tested on linux and osx, probably not working on windows). I wanted to try to recompile the esp8266, apparently it's not the same compiler, and I know I had a lot of trouble making a script that automates everything for the esp32. I don't have esp8266 either. Then if you know a little about it, and you have the time and the material, I can add your scripts into the project. I can help you patch what you need in micropython for support homekit. I attached the script to rebuild the esp 8266, it would probably also be necessary to create the script getFirmware8266.sh, which would look for the right compiler.

**Comment by baracudaz** [comment]
Sure that will do. As it turns out getting the micropython to compile for [esp8266](https://github.com/micropython/micropython/tree/master/ports/esp8266) is fairly straightforward especially with [docker](https://hub.docker.com/r/larsks/esp-open-sdk) image. Here is what I did:
```
docker pull larsks/esp-open-sdk
git clone https://github.com/micropython/micropython.git
cd micropython
export MAKE="docker run --rm -v $HOME:$HOME -u $UID -w $PWD larsks/esp-open-sdk make"
$MAKE -C ports/esp8266 submodules
$MAKE -C mpy-cross
$MAKE -C ports/esp8266
```
Voilà! The esp8266 firmware is build! Now onto merging your code ;)

**Comment by remibert** [comment]
I installed docker on osx, and tried your commands, but it didn't work. I do not know Docker, I watched tutorials on the net, I did not do better. After I looked at the differences between esp32 and esp8266, it's not just a patch, there are a lot of adaptations to be made. Without hardware, not too much time at the moment, without any certainty that on this small processor it works, sorry I could not do more for the moment. All the patches to support homekit on esp32 are available in the "patch/c" and "modules/lib/homekit" directories, maybe if you can manage to compile, patch the makefiles and the sources, to see what happens.

**Comment by katadelos** [comment]
I attempted to add HomeKit support for ESP8266 boards the other night and am reasonably certain that it's not possible. The main issue is that the SDK used to build MicroPython for the ESP8266 is incompatible with `esp-homekit-sdk`; you'd likely come up against resource constraints even if the problems with SDK differences could be resolved.

I've created a repository that contains all the necessary patches and changes needed to build the `homekit` module separately from the pycameresp project here: https://github.com/katadelos/micropython-esp32-homekit

**Comment by remibert** [comment]
I had tried on my side, and I had also difficulties of this kind. But since it wasn't a priority for me, I put it off until later. I also had some inability to get it to work in conjunction with the camera on the esp32cam, the homekit server needs enough call stack to work, and the call stack can only be internal ram of esp32 (not spiram). With Micropython, there is only 100kb left, on an esp8266 the rest is only 32kb. In any case it would have been very limited to make it work under micropython. Thanks for isolating the homekit part, I think it might interest people.

**Comment by remibert** [comment]
Not possible
