### ISSUE TITLE
Lolin D32 Pro - Working

### ISSUE THREAD

**Issue by mrmay-dev** [remibert/pycameresp#4]
Hello @remibert , I have few ESP32 boards that I'm playing with. I've done all my IoT learning with [Tasmota ](https://tasmota.github.io/docs/) and [Home Accessory Architect (HAA)](https://github.com/RavenSystem/esp-homekit-devices) and a little with [Circuit Python](https://circuitpython.org/). I'm really excited to learn Micropython and HomeKit with your build. I don't know enough (yet) to make my own builds. Merci beaucoup!

- **[Lolin D32 Pro](https://www.wemos.cc/en/latest/d32/d32_pro.html):** Installed with CamFlasher, running V3 of the GENERIC_SPIRAM-firmware.bin. It installs, creates the access point and takes changes in configuration. Have not run any micropython code yet.

**Comment by remibert** [comment]
Hello, 

I put some examples for homekit (https://github.com/remibert/pycameresp/tree/main/examples/homekit <https://github.com/remibert/pycameresp/tree/main/examples/homekit>). I advise not change in the main.py the part which manages the wifi, it allows automatic recovery when the radio lost (and this unfortunately happens from time to time). Have a good day.

**Comment by hha1** [comment]
Hello remibert, thanks for your contributions. I successfully compiled this project according to this contribution and ran the examples successfully, but there is no bridge accessory in your examples. I wonder if you can add this instance like C? It's too hard for me. I'm look forward to your reply sincerely, thanks a lot.

**Comment by remibert** [comment]
Hello, apparently there is a C example in the source code esp-homekit-sdk/examples/bridge/main/app_main.c, so technically it should be possible. I know that a fork was made on pycameresp to extract homekit, maybe he made this evolution. Currently I'm busy on other things, so I'm not promising anything in the short term.
